"""home1

Revision ID: 49476541a226
Revises: 422eeb0b5a79
Create Date: 2026-02-19 00:46:59.209599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49476541a226'
down_revision: Union[str, Sequence[str], None] = '422eeb0b5a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orderproducts_order_id_fkey'), 'orderproducts', type_='foreignkey')
    op.create_foreign_key(None, 'orderproducts', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderproducts', type_='foreignkey')
    op.create_foreign_key(op.f('orderproducts_order_id_fkey'), 'orderproducts', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
